# Assignment 02:  Python basics

The purpose of this assignment is learn the fundamentals of Python programming, including:

1. Basic math
1. Variables
1. Lists, tuples and arrays
1. Packages: `math` and `numpy`
1. Functions

___

### Example problem

Q. Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    4 \times 5
\end{eqnarray*}$</center>

### Answer to example problem:

In [1]:
print( 4 * 5 )

20


___

# (1)  Basic math

**Question 1**:   Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    (3 + 1) \times 2
\end{eqnarray*}$</center>

In [1]:
print((3+1)*2)

8


**Question 2**:   Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    (4 + 6) ^ 2
\end{eqnarray*}$</center>

In [2]:
print((4+6)**2)

100


**Question 3**:   Use Python to calculate and print the result of:

<br>

<center>$\begin{eqnarray*}
    \frac{ (3 + 1) \times 2 }{ (4 + 6) ^ 2 }
\end{eqnarray*}$</center>

In [3]:
print(((3+1)*2)/(4+6)**2)

0.08


___

# (2)  Variables

**Question 4**:   Use Python to calculate then print the value of `y`.

<br>

<center>$\begin{eqnarray*}
    x &=& 5 \\
    y &=& (x^2 + 1)
\end{eqnarray*}$</center>

In [4]:
x=5
y=(x**2 + 1)
print(y)

26


**Question 5**:   Use Python to calculate then print the value of `y`.

<br>

<center>$\begin{eqnarray*}
    a &=& 5 \\
    b &=& 10 \\
    c &=& 20 \\
    x &=& -1 \\
    y &=& (ax^2 + bx + c)
\end{eqnarray*}$</center>

In [5]:
a = 5; b = 10; c= 20; x=-1;
y = (a*x**2) + (b*x) + c
print(y)

15


**Question 6**:   Use Python to calculate then print the value of `y`.

<br>

<center>$\begin{eqnarray*}
    x_0 &=& 50 \\
    x_1 &=& 3 x_0 - 50\\
    y &=& \left(\frac{x_0}{x_1}\right)^2
\end{eqnarray*}$</center>

In [6]:
x0 = 50; x1= 3*x0 - 50
y = (x0/x1)**2
print(y)

0.25


___

# (3) Lists and tuples

**Question 7**:   Use Python to construct `x` as a **list**, then print its **second** value.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}10 & 8 & 20 & 6 & 30\end{bmatrix}
\end{eqnarray*}$</center>

In [7]:
x = [10,8,20,6,30]
print(x[1])

8


**Question 8**:   Use Python to construct `x` as a **tuple**, then print its **last** value.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{pmatrix}5 & 2 & 1\end{pmatrix}
\end{eqnarray*}$</center>

In [8]:
x = (5,2,1)
print(x[-1])

1


**Question 9**:   Use Python to construct `x` as a **list** of **tuples**, then print the **last** tuple.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}\begin{pmatrix}5 & 2 & 1\end{pmatrix}, \begin{pmatrix}1 & 3 & 3\end{pmatrix}, \begin{pmatrix}0 & -1 & -2\end{pmatrix}\end{bmatrix}
\end{eqnarray*}$</center>

In [9]:
x = [(5,2,1),(1,3,3),(0,-1,-2)]
print(x[-1])

(0, -1, -2)


**Question 10**:   Use Python to create an empty list `x`, then use three `append` commands to create and print the following list. 

**NOTE!**: your Python code should have **five** commands including three `append` commands and one `print` command.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5 & \begin{pmatrix}1 & 2\end{pmatrix}  & \begin{bmatrix}4 & 5 & 6\end{bmatrix}\end{bmatrix}
\end{eqnarray*}$</center>

In [13]:
x = []
x.append(5)
x.append((1,2))
x.append([4,5,6])
print(x)

[5, (1, 2), [4, 5, 6]]


___

# (4) Packages: math and numpy

### `math`

**Question 11**:   Use the `math` package to calculate `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \sin(\pi/2) - \cos(\pi) 
\end{eqnarray*}$</center>

In [2]:
import math
x = math.sin(math.pi/2)-math.cos(math.pi)
print(x)

2.0


**Question 12**:   Use the `math` package to calculate `y`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x_0 &=& 3\\
    x_1 &=& 4\\
    y &=& \sqrt{x_0^2 + x_1^2}
\end{eqnarray*}$</center>

In [21]:
x0=3; x1=4
y=math.sqrt(x0**2 + x1**2)
print(y)

5.0


**Question 13**:   Use the `math` package to calculate `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& e ^ {\log(10) }
\end{eqnarray*}$</center>

In [7]:
x = math.exp(math.log10(10))
print(x)

2.718281828459045


### `numpy`

**Question 14**:    Use the `numpy` package to construct the following 1D array. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5 & 2 & 1\end{bmatrix}
\end{eqnarray*}$</center>

In [3]:
import numpy as np
x = np.array([5,2,1])
print(x)

[5 2 1]


**Question 15**:    Use the `numpy` package to construct the following 2D array. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5 & 2 & 1\\ 1 & 3 & 3\\ 0 & -1 & -2\end{bmatrix}
\end{eqnarray*}$</center>

In [27]:
x = np.array([[5,2,1],[1,3,3],[0,-1,-2]])
print(x)

[[ 5  2  1]
 [ 1  3  3]
 [ 0 -1 -2]]


**Question 16**:   Use the `numpy` package to compute `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5\\2\\1\end{bmatrix} + 1
\end{eqnarray*}$</center>

In [4]:
x = np.array([5,2,1]).reshape(3,1) + 1
print(x)

[[6]
 [3]
 [2]]


**Question 17**:   Use the `numpy` package to compute `x`. Print the result.

<br>

<center>$\begin{eqnarray*}
    x &=& \begin{bmatrix}5\\2\\1\end{bmatrix} + \begin{bmatrix}3\\-4\\8\end{bmatrix}
\end{eqnarray*}$</center>

In [5]:
x = np.array([5,2,1]).reshape(3,1) + np.array([3,-4,8]).reshape(3,1)
print(x)

[[ 8]
 [-2]
 [ 9]]


___

# (5) Functions

**Question 18**:   Create a function called `myfunction` that calculates $f(x)$. Use this function to calculate $f(x)$ for $x=5$. Print the result.

<br>

<center>$\begin{eqnarray*}
    f(x) &=& 2(x - 1) + 5
\end{eqnarray*}$</center>

In [6]:
def myfunction(x):
    f_x = 2*(x-1) + 5
    return f_x
print(myfunction(5))

13


**Question 19**:   Create a function called `two_argument_function` that calculates $f(a, b)$. Use this function to calculate $f(a, b)$ for $a=3$ and $b=2$. Print the result.

<br>

<center>$\begin{eqnarray*}
    f(a, b) &=& b^a + 1
\end{eqnarray*}$</center>

In [7]:
def two_argument_function(a,b):
    f_ab = b**a + 1
    return f_ab
print(two_argument_function(3,2))

9


**Question 20**:   Create a function called `add_vectors` that calculates $f(\boldsymbol{x}_0, \boldsymbol{x}_1)$. Use this function to calculate $f(\boldsymbol{x}_0, \boldsymbol{x}_1)$ for $\boldsymbol{x}_0=\begin{bmatrix}5\\2\\1\end{bmatrix}$ and $\boldsymbol{x}_1=\begin{bmatrix}1\\2\\10\end{bmatrix}$. Print the result.

<br>

<center>$\begin{eqnarray*}
    f(\boldsymbol{x}_0, \boldsymbol{x}_1) &=&  \boldsymbol{x}_0 + \boldsymbol{x}_1
\end{eqnarray*}$</center>

In [12]:
def add_vectors(x0,x1):
    f_x0x1 = x0 + x1
    return f_x0x1
print(add_vectors(np.array([[5],[2],[1]]),np.array([[1],[2],[10]])))

[[ 6]
 [ 4]
 [11]]


**Question 21**:   Create a Python function that represent the following mathematical function:

<br> 

<center>$\begin{eqnarray*}
    f(\boldsymbol{a}, b, c) &=& b\boldsymbol{a} + \begin{bmatrix}0\\c\\0\end{bmatrix}
\end{eqnarray*}$</center>

<br> 

Note that $\boldsymbol{a}$ is a vector, and that $b$ and $c$ are scalars.

<br>

Use the function you created to calculate $f(\boldsymbol{a},b,c)$ for: $\boldsymbol{a} = \begin{bmatrix}1\\0\\2\end{bmatrix}$, $b=5$ and $c$=10.

Print your solution.

<br> 



In [15]:
def func(a,b,c):
    f = b*a + np.array([0,c,0]).reshape(3,1)
    return f
print(func(np.array([[1],[0],[2]]),5,10))


[[ 5]
 [10]
 [10]]


Very good work! Superb Python coding!

I only have two minor suggestions:

(1) Please avoid using multiple statements on one line like this:

x0 = 50; x1= 3*x0 - 50
It will be much easier to read and debug your code if you use one command per line, like this:

x0 = 50
x1 = 3*x0 - 50
 

(2) I also suggest using 1D arrays wherever possible; in Question 20 & 21 you have used column vectors; this is OK in general, and is very important in other programming languages. In most Python applications it is unnecessary to distinguish row vectors from column vectors, so usually just a 1D vector is best. The ONLY time it may be necessary to use column vectors is when conducting linear algebra (e.g. multiplying a matrix by a vector ). In all other cases I've seen, a 1D array is better. Your code for Question 20, for example would change from this:

print(add_vectors(np.array([[5],[2],[1]]),np.array([[1],[2],[10]])))
to this:

print(   add_vectors( np.array([5,2,1]) , np.array([1,2,10]) )   )
Easy-to-read code like this will become increasingly important as we move forward this semester!