# Quiz 01

Refer to Lessons 01-06 in the [open textbook](https://github.com/0todd0000/OpenBook-DataAnalysisPracticeInPythonAndJupyter) when completing this quiz

<br>

**Instructions**:

* Enter answers in the "<i>Enter answer here</i>" cells below.
* Do NOT create or delete any cells.
* Do NOT change cell types (e.g. from `Markdown` to `Code`).

<br>

___

<br>

<span style="color:#007DD3"><b>Question 1:</b>   What is the Markdown code for writing "Subtitle" as a Level 2 heading?</span>

<br>

## Subtitle

<br>

<span style="color:#007DD3"><b>Question 2:</b>   What are the mean and standard deviation values for the standard normal distribution?</span>

<br>

mean = 0  
standard = 1

<br>

<span style="color:#007DD3"><b>Question 3:</b>   Write a Python function that represents the following equation: &nbsp; &nbsp; $f(x) = 5(x^2 - 1) + 1$</span>

<br>

In [ ]:
y = 5 * ( x**2 - 1 ) + 1

<br>

<span style="color:#007DD3"><b>Question 4:</b>   Use numpy to caluculate the average of the following numbers: 10, 15, 12, 14, 16, 15, 19</span>

<br>

In [2]:
import numpy as np
average = np.mean([ 10, 15, 12, 14, 16, 15, 19])
print ( average )

14.428571428571429


<br>

<span style="color:#007DD3"><b>Question 5:</b>   Enter Python code for creating a <code>(5, 3)</code> array of random numbers from the standard normal distribution (i.e., 5 rows and 3 columns)</span>

<br>

In [3]:
x = np.random.randn( 5, 3 )
print( x )

[[ 0.15865752  0.95300289  0.46427774]
 [ 1.0661649   0.16504496  0.18883702]
 [ 1.55325741 -0.646066   -1.55861913]
 [-2.20069989  1.55043612 -1.47839363]
 [ 1.37050248 -0.04316961 -1.0559588 ]]


<br>

<span style="color:#007DD3"><b>Question 6:</b>   Enter Python code to extract the middle column from the array you created in the question above.</span>

<br>

In [4]:
a = x.T[1]
print ( a )

[ 0.95300289  0.16504496 -0.646066    1.55043612 -0.04316961]


<br>

<span style="color:#007DD3"><b>Question 7:</b>   What function(s) can be used to set the X-axis and Y-axis labels in a Matplotlib figure?</span>

<br>

plt.xlabel(" ")  
plt.ylabel(" ")

<br>

<span style="color:#007DD3"><b>Question 8:</b>   What does "parse" mean?</span>

<br>

It is the process of converting a pieces of python program to machine language to analyze  the correct syntax of the code.

<br>

<span style="color:#007DD3"><b>Question 9:</b>   What NumPy and Pandas functions can be used to read well-formatted CSV files? List one NumPy function and one Pandas function. ("<i>well-formatted</i>" means that there are no errors in the CSV file, for example extra commas, missing values, or empty lines) </span>

<br>

a = np.loadtxt(" ", delimeter = ",")  
b = pd.read_csv(" ")

<br>

<span style="color:#007DD3"><b>Question 10:</b>   What is a script?</span>

<br>

A script is a .py (ASCII) file, containing sequence of arbitary python commands to solve a specific programming problem. 

<br>

<span style="color:#007DD3"><b>Question 11:</b>   What extension do Python scripts have?  (an <a href="https://en.wikipedia.org/wiki/Filename_extension">extension</a> is the set of characters that follow the final period <code>.</code> in a file name)</span>

<br>

.py is used

<br>

<span style="color:#007DD3"><b>Question 12:</b>   What command can be used in a Jupyter cell to run a script?</span>

<br>

%run ~.py  
~ = name of the script

<br>

<span style="color:#007DD3"><b>Question 13:</b>   Which is the best strategy? (Choose the best answer)</span>



<span style="color:#007DD3">1. Always show all parsing and analysis code in a single notebook.</span>

<span style="color:#007DD3">2. Separate parsing and analysis code into separate notebooks and/or scripts.</span>

<span style="color:#007DD3">3. Never save your analysis code in scripts.</span>

<span style="color:#007DD3">4. Always use a single notebook for all reports.</span>

<br>

2.

Very good!

 

Question 6: Minor comment: your answer is correct, but it is usually a bit easier to read an array slicing command like this:

a = x[:,1]
 

Question 8: -1 Incorrect. "Parse" means reading and interpreting. Your answer refers to "compiling" and not "parsing".

 

Otherwise excellent!

 